version: '3.8'
services:
  web:
    build: .
    command: python server_local.py
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx_limit.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
